/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.ComponentOrientation;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author amnassar
 */
public class Home2 extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    LoginForm1 l;
    PreparedStatement pst;
    ResultSet rs;
    private ImageIcon icon;
    public String nameee = null;
    public String typee = null;
    public String oldneww = null;
    public String sectionn = null;
    public String datee;
    public Calendar cal;
    String dayyy;

    public Home2(String type, String username, String oldnew, String section) throws IOException, ParseException {
        initComponents();
         icon = new ImageIcon(getClass().getResource("/Image/mechanic.png"));
        this.setIconImage(icon.getImage());
        typee = type;
        nameee = username;
        oldneww = oldnew;
        sectionn = section;
        jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        Calendar cal = new GregorianCalendar();

        if (typee.equals("admin")) {
            jMenuItem36.setEnabled(true);
        }
        recev1 ad = new recev1(typee, nameee, oldneww, sectionn);
        jDesktopPane1.add(ad).setVisible(true);
        cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);
        int dayy = cal.get(Calendar.DAY_OF_MONTH);
        dayyy = String.valueOf(dayy);
        if (dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
                || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9) {
            dayyy = String.valueOf(dayy);
            dayyy = "0" + dayyy;
        }
        date1.setText(year + "-" + "0" + month + "-" + dayyy);
        datee = date1.getText().toString();

        lateunrecev();
        unrecev();
        rejected();
        finish();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        done = new javax.swing.JButton();
        meall1 = new javax.swing.JButton();
        late = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rejected = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        repairoeder = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(17, 39, 37));
        jPanel1.setMaximumSize(new java.awt.Dimension(1240, 790));
        jPanel1.setMinimumSize(new java.awt.Dimension(1240, 790));
        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 790));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        done.setBackground(new java.awt.Color(138, 203, 195));
        done.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/payment-64.png"))); // NOI18N
        done.setText("انهاء العمل");
        done.setPreferredSize(new java.awt.Dimension(169, 89));
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 220, 70));

        meall1.setBackground(new java.awt.Color(138, 203, 195));
        meall1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        meall1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/attend00.png"))); // NOI18N
        meall1.setText("خروج");
        meall1.setPreferredSize(new java.awt.Dimension(169, 89));
        meall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meall1ActionPerformed(evt);
            }
        });
        jPanel1.add(meall1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, 220, 70));

        late.setBackground(new java.awt.Color(138, 203, 195));
        late.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        late.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/attend00.png"))); // NOI18N
        late.setText("المتاخر ");
        late.setPreferredSize(new java.awt.Dimension(169, 89));
        late.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lateActionPerformed(evt);
            }
        });
        jPanel1.add(late, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, 220, 70));

        jButton2.setBackground(new java.awt.Color(138, 203, 195));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-google-blog-search-64.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 220, 70));

        rejected.setBackground(new java.awt.Color(138, 203, 195));
        rejected.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        rejected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-google-blog-search-64.png"))); // NOI18N
        rejected.setText("المرفوضة");
        rejected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectedActionPerformed(evt);
            }
        });
        jPanel1.add(rejected, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, 220, 70));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(980, 750));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 970, 640));

        repairoeder.setBackground(new java.awt.Color(138, 203, 195));
        repairoeder.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        repairoeder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/student-100.png"))); // NOI18N
        repairoeder.setText("قبول / رفض");
        repairoeder.setPreferredSize(new java.awt.Dimension(169, 89));
        repairoeder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairoederActionPerformed(evt);
            }
        });
        jPanel1.add(repairoeder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 220, 70));

        jButton4.setBackground(new java.awt.Color(138, 203, 195));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-google-blog-search-64.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 510, 220, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1240, 790));
        jLabel2.setMinimumSize(new java.awt.Dimension(1240, 790));
        jLabel2.setPreferredSize(new java.awt.Dimension(1240, 790));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        date1.setText("jLabel1");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(122, 134, 162));

        jMenu1.setText("الرئيسية");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem36.setText("اضافة مستخدم");
        jMenuItem36.setActionCommand("");
        jMenuItem36.setEnabled(false);
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem36);

        jMenuItem37.setText("الرئيسية");
        jMenuItem37.setActionCommand("");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem37);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("تقارير");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem40.setText("المستخدمين");
        jMenuItem40.setActionCommand("");
        jMenuItem40.setEnabled(false);
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem40);

        jMenuItem41.setText("حصر المعدات");
        jMenuItem41.setActionCommand("");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem41);

        jMenuItem42.setText("ايام التوقف لجميع المعدات");
        jMenuItem42.setActionCommand("");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem42);

        jMenuItem43.setText("بيان اصلاحات معدة");
        jMenuItem43.setActionCommand("");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem43);

        jMenuItem44.setText("جميع المعدات الموجودة داخل ورشة");
        jMenuItem44.setActionCommand("");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem44);

        jMenuItem45.setText("بيان نوع الاصلاح");
        jMenuItem45.setActionCommand("");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem45);

        jMenuItem46.setText("طباعة طلب اصلاح");
        jMenuItem46.setActionCommand("");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem46);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void repairoederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairoederActionPerformed
        try {
            jDesktopPane1.removeAll();
            recev1 addd = new recev1(typee, nameee, oldneww, sectionn);
            jDesktopPane1.add(addd).setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_repairoederActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        try {
            jDesktopPane1.removeAll();
            finish addd = new finish(typee, nameee, oldneww, sectionn);
            jDesktopPane1.add(addd).setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_doneActionPerformed

    private void lateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lateActionPerformed

        try {
            jDesktopPane1.removeAll();
            recevnorespond addd = new recevnorespond(typee, nameee, oldneww, sectionn);
            jDesktopPane1.add(addd).setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lateActionPerformed

    private void rejectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectedActionPerformed
        try {
            jDesktopPane1.removeAll();
            recrejected1 addd = new recrejected1(typee, nameee, oldneww, sectionn);
            jDesktopPane1.add(addd).setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_rejectedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*   jDesktopPane1.removeAll();
         msrofat addd = new msrofat();
         jDesktopPane1.add(addd).setVisible(true);*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        /*   try {
         dayfollow m = new dayfollow();
         m.setVisible(true);
         } catch (ParseException ex) {
         Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
         }*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void meall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meall1ActionPerformed
        try {
            new MainPage1(typee, nameee, oldneww, sectionn).setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Home2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_meall1ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        jDesktopPane1.removeAll();
        adduser1 addd = new adduser1();
        jDesktopPane1.add(addd).setVisible(true);

    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        InputStream in = null;
        try {

            in = this.getClass().getResourceAsStream("/reports/users.jasper");
            Map<String, Object> para = new HashMap<String, Object>();
            JasperPrint j = JasperFillManager.fillReport(in, para, DBConnect.appcon);
            JasperViewer.viewReport(j, false);
        } catch (JRException ex) {

            JOptionPane.showMessageDialog(null, ex);
        } finally {
        }
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        InputStream in = null;
        try {

            in = this.getClass().getResourceAsStream("/reports/equipment.jasper");
            Map<String, Object> para = new HashMap<String, Object>();
            JasperPrint j = JasperFillManager.fillReport(in, para, DBConnect.appcon);
            JasperViewer.viewReport(j, false);
        } catch (JRException ex) {

            JOptionPane.showMessageDialog(null, ex);
        } finally {
        }
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        numberofdays m = new numberofdays(oldneww);
        m.setVisible(true);
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        repaireorderdetails m = new repaireorderdetails();
        m.setVisible(true);
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        InputStream in = null;
        try {

            in = this.getClass().getResourceAsStream("/reports/inshop.jasper");
            Map<String, Object> para = new HashMap<String, Object>();
            para.put("oldnew", oldneww);
            JasperPrint j = JasperFillManager.fillReport(in, para, DBConnect.appcon);
            JasperViewer.viewReport(j, false);
        } catch (JRException ex) {

            JOptionPane.showMessageDialog(null, ex);
        } finally {
        }
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
        bytype m = new bytype(oldneww);
        m.setVisible(true);
    }//GEN-LAST:event_jMenuItem45ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        printdoc m = new printdoc();
        m.setVisible(true);
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date1;
    public javax.swing.JButton done;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton4;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton late;
    public javax.swing.JButton meall1;
    public javax.swing.JButton rejected;
    public javax.swing.JButton repairoeder;
    // End of variables declaration//GEN-END:variables

    public void unrecev() {
        if (typee.equals("admin")) {
            try {
                String sqll = "SELECT count(seriall) as x FROM karem.repaireorder where id in (select id FROM karem.repaireorder where statuss IN ('resend') ) OR statuss in ('draft','resend')  and typee='" + oldneww + "'";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {
                    repairoeder.setText(repairoeder.getText() + " ( " + rs.getString("x") + " )");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                String sqll = "SELECT count(seriall) as x FROM karem.repaireorder where id in (select id FROM karem.repaireorder where statuss IN ('resend') and worker='" + nameee + "' ) OR statuss in ('draft','resend')  and typee='" + oldneww + "'";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {
                    repairoeder.setText(repairoeder.getText() + " ( " + rs.getString("x") + " )");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void lateunrecev() {
        if (typee.equals("admin")) {
            try {
                String sqll = "SELECT count(seriall) as x FROM karem.repaireorder where datee not in "
                        + "(select  datee FROM karem.repaireorder where datee between DATE_ADD('" + datee + "', INTERVAL -2 DAY) and '" + datee + "') "
                        + "and typee='" + oldneww + "'  and statuss = 'draft' order by id";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {
                    late.setText(late.getText() + " ( " + rs.getString("x") + " )");

                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                String sqll = "SELECT count(seriall) as x FROM karem.repaireorder where datee not in "
                        + "(select  datee FROM karem.repaireorder where datee between DATE_ADD('" + datee + "', INTERVAL -2 DAY) and '" + datee + "') "
                        + "and typee='" + oldneww + "'  and statuss = 'draft' order by id";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {
                    late.setText(late.getText() + " ( " + rs.getString("x") + " )");

                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void finish() {
        if (typee.equals("admin")) {
            try {
                String sqll = "SELECT count(seriall) as x FROM karem.repaireorder  where statuss = 'underconstruction'  order by id";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {

                    done.setText(done.getText() + " ( " + rs.getString("x") + " )");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                String sqll = "SELECT count(seriall) as x FROM karem.repaireorder  where statuss = 'underconstruction' and worker = '" + nameee + "' order by id";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {

                    done.setText(done.getText() + " ( " + rs.getString("x") + " )");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void rejected() {
        if (typee.equals("admin")) {
            try {
                String sqll = "SELECT  count(seriall) as x FROM karem.repaireorder  where statuss = 'rejectedtorecev'   order by id";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {
                    rejected.setText(rejected.getText() + " ( " + rs.getString("x") + " )");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                String sqll = "SELECT  count(seriall) as x FROM karem.repaireorder  where statuss = 'rejectedtorecev'  and worker ='" + nameee + "' order by id";
                pst = (PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
                rs = pst.executeQuery();
                if (rs.next()) {
                    rejected.setText(rejected.getText() + " ( " + rs.getString("x") + " )");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
