/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */
public final class recrejected1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
    PreparedStatement pst ;
    ResultSet rs;
     public String y ;
     public String check;
      public String datee;
      public String fulldatee;
      public  Calendar cal;
      public String pphone1;
      public String pphone2;
      public String ppp2;
      public String ppp1;
      public String ttt1;
      public String ttt2;
      String dayyy ;
       public  String usernamee=null;
     public  String typee=null;
     public  String oldneww=null;
     public  String sectionn=null;
      ButtonGroup G ;
      public String fulll;
    
   
    public recrejected1(String type,String username , String oldnew , String section ) throws ParseException {
        initComponents();
         typee=type;
        usernamee=username;
        oldneww=oldnew;
        sectionn=section;
          clear();
         itemm();
      AutoCompleteDecorator.decorate(cmserial);
         
          if(typee.equals("admin"))
        {
          
        }
        cal = new GregorianCalendar();
               int month=cal.get(Calendar.MONTH)+1;
             int year = cal.get(Calendar.YEAR);
                 int dayy =cal.get(Calendar.DAY_OF_MONTH);
             dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
           date1.setText(year+"-"+"0"+month+"-"+dayyy);
           datee=date1.getText().toString();
            TimeZone tz = TimeZone.getTimeZone("GMT+02");
             Calendar c = Calendar.getInstance(tz);
             String time = String.format("%02d" , c.get(Calendar.HOUR_OF_DAY))+":"+
                     String.format("%02d" , c.get(Calendar.MINUTE));
              fulldatee=datee+" "+time;
        
         G = new ButtonGroup();
        G.add(full);
        G.add(part);
        part.setSelected(true);
        tablelord2();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        save1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        serialid1 = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        workremark = new javax.swing.JTextArea();
        afsha = new javax.swing.JCheckBox();
        framel = new javax.swing.JCheckBox();
        mohrk = new javax.swing.JCheckBox();
        hydrolek = new javax.swing.JCheckBox();
        khrba = new javax.swing.JCheckBox();
        smkra = new javax.swing.JCheckBox();
        dhanat = new javax.swing.JCheckBox();
        hwa = new javax.swing.JCheckBox();
        redater = new javax.swing.JCheckBox();
        sroge = new javax.swing.JCheckBox();
        zogag = new javax.swing.JCheckBox();
        fhs = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jkman = new javax.swing.JCheckBox();
        zyot = new javax.swing.JCheckBox();
        tshem = new javax.swing.JCheckBox();
        wire = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        hour = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        etarat = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        rejected = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        filter = new javax.swing.JCheckBox();
        full = new javax.swing.JRadioButton();
        part = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expected = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();
        sectionnn = new javax.swing.JTextField();
        typeee = new javax.swing.JTextField();
        cmserial = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel11.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save1.setBackground(new java.awt.Color(138, 203, 195));
        save1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save1.setText("طباعة");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel11.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 180, 40));

        tdetails.setBackground(new java.awt.Color(138, 203, 195));
        tdetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "المسئول", "نوع الامر", "التاريخ", "القسم", "نوع المعدة", "كود المعدة", "اسم المعدة", "الرقم التسلسلي", "id"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(1).setMinWidth(100);
            tdetails.getColumnModel().getColumn(1).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(1).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(7).setMinWidth(100);
            tdetails.getColumnModel().getColumn(7).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(7).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(8).setMinWidth(1);
            tdetails.getColumnModel().getColumn(8).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(8).setMaxWidth(1);
        }

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 860, 360));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel20.setText("طلبات الاصلاحات المرفوضة");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 440, 60));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid1.setText("jLabel1");
        jPanel11.add(serialid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        serial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serial.setForeground(new java.awt.Color(255, 255, 255));
        serial.setText("Serial");
        jPanel11.add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 160, 40));

        date2.setText("date");
        jPanel11.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jTabbedPane1.addTab("القائمة", jPanel11);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel38.setText("الاجرائات");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 80, 30));

        workremark.setColumns(20);
        workremark.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        workremark.setRows(5);
        jScrollPane4.setViewportView(workremark);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 350, -1));

        afsha.setBackground(new java.awt.Color(138, 203, 195));
        afsha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        afsha.setText("عفشة");
        jPanel10.add(afsha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        framel.setBackground(new java.awt.Color(138, 203, 195));
        framel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        framel.setText("فرامل");
        jPanel10.add(framel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 70, -1));

        mohrk.setBackground(new java.awt.Color(138, 203, 195));
        mohrk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mohrk.setText("محرك");
        jPanel10.add(mohrk, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        hydrolek.setBackground(new java.awt.Color(138, 203, 195));
        hydrolek.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hydrolek.setText("هيدروليك");
        jPanel10.add(hydrolek, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, -1));

        khrba.setBackground(new java.awt.Color(138, 203, 195));
        khrba.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        khrba.setText("كهرباء");
        jPanel10.add(khrba, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 60, -1));

        smkra.setBackground(new java.awt.Color(138, 203, 195));
        smkra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        smkra.setText("سمكرة");
        jPanel10.add(smkra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        dhanat.setBackground(new java.awt.Color(138, 203, 195));
        dhanat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dhanat.setText("دهانات");
        jPanel10.add(dhanat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        hwa.setBackground(new java.awt.Color(138, 203, 195));
        hwa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hwa.setText("دائرة هواء");
        jPanel10.add(hwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        redater.setBackground(new java.awt.Color(138, 203, 195));
        redater.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        redater.setText("ريداتير");
        jPanel10.add(redater, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 60, -1));

        sroge.setBackground(new java.awt.Color(138, 203, 195));
        sroge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sroge.setText("سروجي");
        jPanel10.add(sroge, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 70, -1));

        zogag.setBackground(new java.awt.Color(138, 203, 195));
        zogag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zogag.setText("زجاج");
        jPanel10.add(zogag, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 50, -1));

        fhs.setBackground(new java.awt.Color(138, 203, 195));
        fhs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fhs.setText("فحص شهري");
        jPanel10.add(fhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel34.setText("الاسباب المتوقعة");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 120, 30));

        jkman.setBackground(new java.awt.Color(138, 203, 195));
        jkman.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jkman.setText("جكمان");
        jPanel10.add(jkman, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 60, -1));

        zyot.setBackground(new java.awt.Color(138, 203, 195));
        zyot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zyot.setText("زيوت");
        jPanel10.add(zyot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 60, -1));

        tshem.setBackground(new java.awt.Color(138, 203, 195));
        tshem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tshem.setText("تشحيم");
        jPanel10.add(tshem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        wire.setBackground(new java.awt.Color(138, 203, 195));
        wire.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wire.setText("واير");
        jPanel10.add(wire, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, -1));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel36.setText("عدد الساعات");
        jPanel10.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 110, 30));

        hour.setEditable(false);
        hour.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        hour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 90, 30));

        name.setEditable(false);
        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 170, -1));

        etarat.setBackground(new java.awt.Color(138, 203, 195));
        etarat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etarat.setText("اطارات");
        jPanel10.add(etarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 70, -1));

        rejected.setEditable(false);
        rejected.setColumns(20);
        rejected.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rejected.setRows(5);
        jScrollPane5.setViewportView(rejected);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 350, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel37.setText("سبب الرفض");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 110, 30));

        filter.setBackground(new java.awt.Color(138, 203, 195));
        filter.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        filter.setText("فلتر");
        jPanel10.add(filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 70, 20));

        full.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        full.setText("اصلاح شامل");
        full.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullActionPerformed(evt);
            }
        });
        jPanel10.add(full, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        part.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        part.setText("جزئي");
        part.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partActionPerformed(evt);
            }
        });
        jPanel10.add(part, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel35.setText("تفاصيل العطل");
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 120, 30));

        code.setEditable(false);
        code.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 110, 30));

        save.setBackground(new java.awt.Color(138, 203, 195));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setText("اعادة ارسال");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel10.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 180, 40));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("كود الطلب");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 110, 30));

        expected.setEditable(false);
        expected.setColumns(20);
        expected.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        expected.setRows(5);
        jScrollPane1.setViewportView(expected);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 310, -1));

        details.setEditable(false);
        details.setColumns(20);
        details.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        details.setRows(5);
        jScrollPane2.setViewportView(details);

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 310, -1));

        sectionnn.setEditable(false);
        sectionnn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sectionnn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(sectionnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 240, -1));

        typeee.setEditable(false);
        typeee.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        typeee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(typeee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 100, -1));

        cmserial.setEditable(true);
        cmserial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmserial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmserialActionPerformed(evt);
            }
        });
        jPanel10.add(cmserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 220, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        date1.setText("date");
        jPanel10.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jTabbedPane1.addTab("اعادة ارسال", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("استلام - رفض");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullActionPerformed
        afsha.setEnabled(false);
        afsha.setSelected(false);
        framel.setEnabled(false);
        framel.setSelected(false);
        mohrk.setEnabled(false);
        mohrk.setSelected(false);
        hydrolek.setEnabled(false);
        hydrolek.setSelected(false);
        khrba.setEnabled(false);
        khrba.setSelected(false);
        smkra.setEnabled(false);
        smkra.setSelected(false);
        dhanat.setEnabled(false);
        dhanat.setSelected(false);
        hwa.setEnabled(false);
        hwa.setSelected(false);
        redater.setEnabled(false);
        redater.setSelected(false);
        sroge.setEnabled(false);
        sroge.setSelected(false);
        zogag.setEnabled(false);
        zogag.setSelected(false);
        fhs.setEnabled(false);
        fhs.setSelected(false);
        jkman.setEnabled(false);
        jkman.setSelected(false);
        zyot.setEnabled(false);
        zyot.setSelected(false);
        filter.setEnabled(false);
        filter.setSelected(false);
        tshem.setEnabled(false);
        tshem.setSelected(false);
        wire.setEnabled(false);
        wire.setSelected(false);
        etarat.setEnabled(false);
        etarat.setSelected(false);
    }//GEN-LAST:event_fullActionPerformed

    private void partActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partActionPerformed
        afsha.setEnabled(true);
        afsha.setSelected(false);
        framel.setEnabled(true);
        framel.setSelected(false);
        mohrk.setEnabled(true);
        mohrk.setSelected(false);
        filter.setEnabled(true);
        filter.setSelected(false);
        hydrolek.setEnabled(true);
        hydrolek.setSelected(false);
        khrba.setEnabled(true);
        khrba.setSelected(false);
        smkra.setEnabled(true);
        smkra.setSelected(false);
        dhanat.setEnabled(true);
        dhanat.setSelected(false);
        hwa.setEnabled(true);
        hwa.setSelected(false);
        redater.setEnabled(true);
        redater.setSelected(false);
        sroge.setEnabled(true);
        sroge.setSelected(false);
        zogag.setEnabled(true);
        zogag.setSelected(false);
        fhs.setEnabled(true);
        fhs.setSelected(false);
        jkman.setEnabled(true);
        jkman.setSelected(false);
        zyot.setEnabled(true);
        zyot.setSelected(false);
        tshem.setEnabled(true);
        tshem.setSelected(false);
        wire.setEnabled(true);
        wire.setSelected(false);
        etarat.setEnabled(true);
        etarat.setSelected(false);
    }//GEN-LAST:event_partActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

                       String namee = name.getText();
           String typee= typeee.getText();
           String codee = code.getText();
           String section = sectionnn.getText();
           String kind = "جزئي";
           String afshaa = "No"; String framell = "No"; String mohrkk = "No";String hydrolekk = "No";String khrbaa = "No";String filterr = "No";String smkraa = "No";String dhanatt = "No";String hwaa = "No";
           String redaterr = "No";String srogee = "No";String zogagg = "No";String fhss = "No";String jkmann = "No";String zyott = "No";String tshemm = "No";String wiree = "No";
           String etaratt = "No";
           String detailss= details.getText();
           String expectedd = expected.getText();
           String seriall = cmserial.getSelectedItem().toString();
           fulll="";
            if(full.isSelected())  {kind = "اصلاح شامل"; fulll=fulll + "اصلاح شامل "; }  if(filter.isSelected())  {filterr = "فلتر"; fulll=fulll + "فلتر"; }
            if(afsha.isSelected()) {afshaa = "Yes";  fulll=fulll + "عفشة "; }  if(framel.isSelected()) { framell = "Yes"; fulll=fulll + "فرامل "; }  if(mohrk.isSelected()) { mohrkk = "Yes"; fulll=fulll + "محرك "; }
           if(hydrolek.isSelected()) { hydrolekk = "Yes"; fulll=fulll + "هيدروليك "; }  if(khrba.isSelected()){ khrbaa = "Yes"; fulll=fulll + "كهربة ";} if(smkra.isSelected()) {  smkraa = "Yes";fulll=fulll + "سمكرة "; }
           if(dhanat.isSelected())  { dhanatt = "Yes";fulll=fulll + "دهانات ";  } if(hwa.isSelected()) { hwaa = "Yes";fulll=fulll + "دائرة هواء "; } if(redater.isSelected())  { redaterr = "Yes";fulll=fulll + "ريداتير ";  }
           if(sroge.isSelected())  {srogee = "Yes";fulll=fulll + "سروجي ";   } if(zogag.isSelected()){ zogagg = "Yes";fulll=fulll + "زجاج ";  } if(fhs.isSelected()){ fhss = "Yes"; fulll=fulll + "فحص شهري "; }
           if(jkman.isSelected()) {jkmann = "Yes"; fulll=fulll + "جكمان "; } if(zyot.isSelected()){  zyott = "Yes"; fulll=fulll + "زيوت ";}  
           if(tshem.isSelected()){  tshemm = "Yes";fulll=fulll + "تشحيم "; } if(wire.isSelected()) {wiree = "Yes";fulll=fulll + "واير "; } 
           if(etarat.isSelected()) { etaratt = "Yes";fulll=fulll + "اطارات ";  }
            try {
                String sql1 = "UPDATE karem.repaireorder SET statuss='finished' ,kind='"+kind+"',afhsa='"+afshaa+"',workremark='"+workremark.getText()+"',framel='"+framell+"',mohrk='"+mohrkk+"',"
                        + "hydrolek='"+hydrolekk+"',khrba='"+khrbaa+"'"
                        + ",smkra='"+smkraa+"',filter='"+filterr+"',dhanat='"+dhanatt+"',hwa='"+hwaa+"',redater='"+redaterr+"',sroge='"+srogee+"',zogag='"+zogagg+"',"
                        + "fhs='"+fhss+"',jkman='"+jkmann+"',zyot='"+zyott+"'"
                        + ",tshem='"+tshemm+"',wire='"+wiree+"',etarat='"+etaratt+"',full='"+fulll+"'"
                        + "WHERE seriall= '"+cmserial.getSelectedItem().toString()+"'";
                pst=(PreparedStatement) DBConnect.appcon.prepareStatement(sql1);
                pst.executeUpdate();
                        
                String sql = "INSERT INTO karem.logs (eqname,typee,section,codee,seriall,datee,fulldate,statuss,details,expected,afhsa,framel"
                   + ",mohrk,hydrolek,khrba,smkra,dhanat,hwa,redater,sroge,zogag,fhs,jkman,zyot,tshem,wire,etarat,kind,full,filter)"
                   + " VALUES ('"+namee+"','"+typee+"','"+section+"','"+codee+"','"+seriall+"','"+datee+"','"+fulldatee+"','finished','"+detailss+"','"+expectedd+"',"
                   + "'"+afshaa+"','"+framell+"','"+mohrkk+"','"+hydrolekk+"','"+khrbaa+"','"+smkraa+"','"+dhanatt+"','"+hwaa+"','"+redaterr+"','"+srogee+"','"+zogagg+"','"+fhss+"'"
                   + ",'"+jkmann+"','"+zyott+"','"+tshemm+"','"+wiree+"','"+etaratt+"','"+kind+"','"+fulll+"','"+filterr+"')";
           pst = (PreparedStatement)DBConnect.appcon.prepareStatement(sql);
           pst.execute();
           cmserial.removeItem(cmserial.getSelectedItem().toString());
           JOptionPane.showMessageDialog(rootPane, "تم اعادة الارسال بنجاح");
            InputStream in=null;
      try {
          
          in = this.getClass().getResourceAsStream("/reports/report.jasper");
    Map<String,Object> para = new HashMap<String,Object>();
            para.put("serial",seriall );
           para.put("date",fulldatee );

            JasperPrint j = JasperFillManager.fillReport(in, para,DBConnect.appcon);
            JasperViewer.viewReport(j,false);
      }
     catch (JRException ex) {
        } finally {
        } 
           clear();
            } catch (SQLException ex) {
                Logger.getLogger(recrejected1.class.getName()).log(Level.SEVERE, null, ex);
            }
                   

    }//GEN-LAST:event_saveActionPerformed

    private void cmserialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmserialActionPerformed
        try
        {
            Object obj = evt.getSource();
            if(obj==cmserial)
            {
                if(cmserial.getSelectedItem().toString().trim().isEmpty())
                {
                }
                else
                {
                    try {
                        String sql="SELECT *  FROM karem.repaireorder where seriall='"+cmserial.getSelectedItem().toString()+"'";
                        pst=(PreparedStatement) DBConnect.appcon.prepareStatement(sql);
                        rs=pst.executeQuery();
                        if(rs.next()){
                            rejected.setText(rs.getString("reason"));
                            code.setText(rs.getString("codee"));
                            name.setText(rs.getString("eqname"));
                            typeee.setText(rs.getString("typee"));
                            details.setText(rs.getString("details"));
                            expected.setText(rs.getString("expected"));
                            sectionnn.setText(rs.getString("section"));
                            rejected.setText(rs.getString("reason"));
                            workremark.setText(rs.getString("workremark"));
                            hour.setText(rs.getString("hour"));
                            if(rs.getString("kind").equals("اصلاح شامل"))
                            {
                                full.setSelected(true);
                                clean();
                            }
                            else
                            {
                                part.setSelected(true);
                                if(rs.getString("afhsa").equals("Yes")) {afsha.setSelected(true); } else { afsha.setSelected(false);}
                                 if(rs.getString("filter").equals("Yes")) {filter.setSelected(true); } else { filter.setSelected(false);}
                                if(rs.getString("framel").equals("Yes")) {framel.setSelected(true); } else { framel.setSelected(false);}
                                if(rs.getString("mohrk").equals("Yes")) {mohrk.setSelected(true); } else { mohrk.setSelected(false);}
                                if(rs.getString("hydrolek").equals("Yes")) {hydrolek.setSelected(true); } else { hydrolek.setSelected(false);}
                                if(rs.getString("khrba").equals("Yes")) {khrba.setSelected(true); } else { khrba.setSelected(false);}
                                if(rs.getString("smkra").equals("Yes")) {smkra.setSelected(true); } else { smkra.setSelected(false);}
                                if(rs.getString("dhanat").equals("Yes")) {dhanat.setSelected(true); } else { dhanat.setSelected(false);}
                                if(rs.getString("hwa").equals("Yes")) {hwa.setSelected(true); } else { hwa.setSelected(false);}
                                if(rs.getString("redater").equals("Yes")) {redater.setSelected(true); } else { redater.setSelected(false);}
                                if(rs.getString("sroge").equals("Yes")) {sroge.setSelected(true); } else { sroge.setSelected(false);}
                                if(rs.getString("zogag").equals("Yes")) {zogag.setSelected(true); } else { zogag.setSelected(false);}
                                if(rs.getString("fhs").equals("Yes")) {fhs.setSelected(true); } else { fhs.setSelected(false);}
                                if(rs.getString("jkman").equals("Yes")) {jkman.setSelected(true); } else { jkman.setSelected(false);}
                                if(rs.getString("zyot").equals("Yes")) {zyot.setSelected(true); } else { zyot.setSelected(false);}
                                if(rs.getString("tshem").equals("Yes")) {tshem.setSelected(true); } else { tshem.setSelected(false);}
                                if(rs.getString("wire").equals("Yes")) {wire.setSelected(true); } else { wire.setSelected(false);}
                                if(rs.getString("etarat").equals("Yes")) {etarat.setSelected(true); } else { etarat.setSelected(false);}
                            }
                        }
                    } catch (SQLException ex) {

                    }

                }}
            }
            catch(Exception ex)
            {
          JOptionPane.showMessageDialog(rootPane, ex);
            }
    }//GEN-LAST:event_cmserialActionPerformed

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel =(DefaultTableModel)tdetails.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex=tdetails.getSelectedRow();
        serialid.setText(tmodel.getValueAt(selectrowindex, 7).toString());

    }//GEN-LAST:event_tdetailsMouseClicked

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        InputStream in=null;
      try {
          
          in = this.getClass().getResourceAsStream("/reports/reject.jasper");
    Map<String,Object> para = new HashMap<String,Object>();
            para.put("serial",serialid.getText() );
           para.put("date",fulldatee );

            JasperPrint j = JasperFillManager.fillReport(in, para,DBConnect.appcon);
            JasperViewer.viewReport(j,false);
      }
     catch (JRException ex) {
        } finally {
        } 
    }//GEN-LAST:event_save1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox afsha;
    private javax.swing.JComboBox cmserial;
    private javax.swing.JTextField code;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JTextArea details;
    private javax.swing.JCheckBox dhanat;
    private javax.swing.JCheckBox etarat;
    private javax.swing.JTextArea expected;
    private javax.swing.JCheckBox fhs;
    private javax.swing.JCheckBox filter;
    private javax.swing.JCheckBox framel;
    private javax.swing.JRadioButton full;
    private javax.swing.JTextField hour;
    private javax.swing.JCheckBox hwa;
    private javax.swing.JCheckBox hydrolek;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jkman;
    private javax.swing.JCheckBox khrba;
    private javax.swing.JCheckBox mohrk;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton part;
    private javax.swing.JCheckBox redater;
    private javax.swing.JTextArea rejected;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    private javax.swing.JTextField sectionnn;
    private javax.swing.JLabel serial;
    private javax.swing.JLabel serialid;
    private javax.swing.JLabel serialid1;
    private javax.swing.JCheckBox smkra;
    private javax.swing.JCheckBox sroge;
    private javax.swing.JTable tdetails;
    private javax.swing.JCheckBox tshem;
    private javax.swing.JTextField typeee;
    private javax.swing.JCheckBox wire;
    private javax.swing.JTextArea workremark;
    private javax.swing.JCheckBox zogag;
    private javax.swing.JCheckBox zyot;
    // End of variables declaration//GEN-END:variables
public void clear()
{
    code.setText(""); 
    serialid.setText(""); 
 typeee.setText("");
 
 cmserial.setSelectedIndex(0);
 part.setSelected(true);
  afsha.setEnabled(true);
  details.setText("");
  expected.setText("");
        afsha.setSelected(false);
        framel.setEnabled(true);
        framel.setSelected(false);
        mohrk.setEnabled(true);
        mohrk.setSelected(false);
        hydrolek.setEnabled(true);
        hydrolek.setSelected(false);
        khrba.setEnabled(true);
        khrba.setSelected(false);
        smkra.setEnabled(true);
        smkra.setSelected(false);
        dhanat.setEnabled(true);
        dhanat.setSelected(false);
        hwa.setEnabled(true);
        hwa.setSelected(false);
        redater.setEnabled(true);
        redater.setSelected(false);
        sroge.setEnabled(true);
        sroge.setSelected(false);
        zogag.setEnabled(true);
        zogag.setSelected(false);
        fhs.setEnabled(true);
        fhs.setSelected(false);
        jkman.setEnabled(true);
        jkman.setSelected(false);
        zyot.setEnabled(true);
        zyot.setSelected(false);
        filter.setEnabled(true);
        filter.setSelected(false);
        tshem.setEnabled(true);
        tshem.setSelected(false);
        wire.setEnabled(true);
        wire.setSelected(false);
        etarat.setEnabled(true);
        etarat.setSelected(false);
        sectionnn.setText("");
        rejected.setText("");
        hour.setText("");
        name.setText("");
}

 public void itemm()
   {
        try {
             String sqll = "SELECT * FROM karem.repaireorder  where statuss = 'rejectedtorecev' and worker ='"+usernamee+"' order by id";
              pst=(PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
            rs=pst.executeQuery();
             while(rs.next()){
                String namee = rs.getString("seriall");
                
                cmserial.addItem(namee);
  
             }

         } catch (SQLException ex) {
              
         }
   }
public void tablelord2()
{if(typee.equals("admin"))
{
    cmserial.setEnabled(false);
    save.setEnabled(false);
    try {
           String sqll = "SELECT * FROM karem.repaireorder  where statuss = 'rejectedtorecev' order by id";
              pst=(PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails.getModel(); 
                model.setRowCount(0);
              int k = 0;
                while (rs.next())
                {
                    Object row[] = {
                       rs.getString("username"),
                        rs.getString("kind"),
                        rs.getString("datee"),
                        rs.getString("section"),
                        rs.getString("typee"),
                        rs.getString("codee"),
                        rs.getString("eqname"),
                        rs.getString("seriall"),
                        rs.getString("id"),
                     };
                    model.addRow(row);
                    k++;
                }
                for(int i = k ;i<20;i++)
                {
                 Object rowData[] = {
                       "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                       };
                model.addRow(rowData);
                } 
        }
        catch (SQLException ex) {
            
        }
}
else
    
    try {
           String sqll = "SELECT * FROM karem.repaireorder  where statuss = 'rejectedtorecev'  and worker ='"+usernamee+"' order by id";
              pst=(PreparedStatement) DBConnect.appcon.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails.getModel(); 
                model.setRowCount(0);
              int k = 0;
                while (rs.next())
                {
                    Object row[] = {
                        rs.getString("username"),
                        rs.getString("kind"),
                        rs.getString("datee"),
                        rs.getString("section"),
                        rs.getString("typee"),
                        rs.getString("codee"),
                        rs.getString("eqname"),
                        rs.getString("seriall"),
                        rs.getString("id"),
                     };
                    model.addRow(row);
                    k++;
                }
                for(int i = k ;i<20;i++)
                {
                 Object rowData[] = {
                       "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                       };
                model.addRow(rowData);
                } 
        }
        catch (SQLException ex) {
            
        }
}
public void clean()
{
     afsha.setEnabled(false);
        afsha.setSelected(false);
        framel.setEnabled(false);
        framel.setSelected(false);
        mohrk.setEnabled(false);
        mohrk.setSelected(false);
        hydrolek.setEnabled(false);
        hydrolek.setSelected(false);
        khrba.setEnabled(false);
        khrba.setSelected(false);
        smkra.setEnabled(false);
        smkra.setSelected(false);
        dhanat.setEnabled(false);
        dhanat.setSelected(false);
        hwa.setEnabled(false);
        hwa.setSelected(false);
        redater.setEnabled(false);
        redater.setSelected(false);
        sroge.setEnabled(false);
        sroge.setSelected(false);
        filter.setEnabled(false);
        filter.setSelected(false);
        zogag.setEnabled(false);
        zogag.setSelected(false);
        fhs.setEnabled(false);
        fhs.setSelected(false);
        jkman.setEnabled(false);
        jkman.setSelected(false);
        zyot.setEnabled(false);
        zyot.setSelected(false);
        tshem.setEnabled(false);
        tshem.setSelected(false);
        wire.setEnabled(false);
        wire.setSelected(false);
        etarat.setEnabled(false);
        etarat.setSelected(false);
}
        
}
